---
- name: User ssh Key Creation and Signing
  hosts: hosts
  become: yes
  tasks:
    - name: Generate ssh key for user
      user:
        name: "{{ user_name }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_type: ed25519
        ssh_key_file: "/home/{{ user_name }}/.ssh/id_ed25519"
      become: yes

    - name: Sign the ssh public key with the server's CA
      community.crypto.openssh_cert:
        path: "/home/{{ user_name }}/.ssh/id_ed25519-cert.pub"
        public_key: "/home/{{ user_name }}/.ssh/id_ed25519.pub"
        signing_key: "/etc/ssh/ca_keys/ssh_ca_key"
        type: user
        identifier: "{{ user_name }}"
        valid_from: always
        valid_to: forever
        state: present
      become: yes

    - name: Output the content of certificate
      command: cat "/home/{{ user_name }}/.ssh/id_ed25519-cert.pub"
      register: cert_content
      become: yes

    - name: Display the certificate content
      debug:
        msg: "{{ cert_content.stdout }}"
